package fr.jacototlefranc.energy.view.textures;

public enum TextureName {
    SQUARE_OUTLET,
    SQUARE_WIFI,
    SQUARE_POWERED_WIFI,
    SQUARE_LIGHTBULB,
    SQUARE_POWERED_LIGHTBULB,
    SQUARE_COMPONENT_LINK,
    SQUARE_POWERED_COMPONENT_LINK,
    SQUARE_LINK_LONG,
    SQUARE_CURVE_LINK,
    SQUARE_OUTLINE,
    SQUARE_OUTLINE_POWERED,
    HEXAGONAL_OUTLET,
    HEXAGONAL_WIFI,
    HEXAGONAL_POWERED_WIFI,
    HEXAGONAL_LIGHTBULB,
    HEXAGONAL_POWERED_LIGHTBULB,
    HEXAGONAL_COMPONENT_LINK,
    HEXAGONAL_OUTLINE,
    HEXAGONAL_OUTLINE_POWERED,
}
